# Generated by Django 4.1.6 on 2023-02-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistdomains',
            options={'verbose_name': 'Whitelisted Domain', 'verbose_name_plural': 'Whitelisted Domains'},
        ),
        migrations.AlterModelOptions(
            name='whitelistemails',
            options={'verbose_name': 'Whitelisted Email', 'verbose_name_plural': 'Whitelisted Emails'},
        ),
        migrations.RenameField(
            model_name='whitelistdomains',
            old_name='domail',
            new_name='domain',
        ),
    ]
